/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author HYPERLINKS
 */
public class AccountBalance extends javax.swing.JInternalFrame {
java.sql.Connection con = null;
    ResultSet rs = null;
    java.sql.PreparedStatement pst = null;
    /**
     * Creates new form AccountBalance
     */
    public AccountBalance() {
        initComponents();
    }
    public void clear(){
 jTextFieldacnim.setText("");
jTextFieldname.setText("");
idNumber.setText("");
jTextcontact.setText("");
jTexBalance.setText("");
jCombacytpe.setSelectedIndex(0);}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextcontact = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jTexBalance = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldacnim = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        idNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCombacytpe = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("                                                         Check Balance");

        jDesktopPane1.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Account Balance");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(280, 10, 150, 24);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Account Number");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(40, 60, 88, 14);

        jTextcontact.setEditable(false);
        jTextcontact.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane1.add(jTextcontact);
        jTextcontact.setBounds(160, 150, 190, 20);

        jTextFieldname.setEditable(false);
        jTextFieldname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane1.add(jTextFieldname);
        jTextFieldname.setBounds(160, 90, 380, 20);

        jTexBalance.setEditable(false);
        jTexBalance.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane1.add(jTexBalance);
        jTexBalance.setBounds(160, 180, 190, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Current Account Balance");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(10, 190, 140, 14);

        jTextFieldacnim.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane1.add(jTextFieldacnim);
        jTextFieldacnim.setBounds(160, 60, 230, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(100, 90, 31, 14);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Contact");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(59, 160, 70, 14);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(400, 60, 140, 25);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ID Number");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(70, 120, 75, 14);

        idNumber.setEditable(false);
        idNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane1.add(idNumber);
        idNumber.setBounds(160, 120, 140, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Account Type");
        jDesktopPane1.add(jLabel14);
        jLabel14.setBounds(310, 120, 71, 14);

        jCombacytpe.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jCombacytpe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select Account type-", "Salary Account", "Current Account" }));
        jCombacytpe.setEnabled(false);
        jDesktopPane1.add(jCombacytpe);
        jCombacytpe.setBounds(390, 120, 150, 20);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton2.setText("New Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(180, 250, 140, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 try{

            con = (Connection) DBManager.ConnectDB();


            String sql = "select * from mainaccount where AccountNumber = '" + jTextFieldacnim.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {

                String add1 = rs.getString("Name");
                jTextFieldname.setText(add1);
                String add11 = rs.getString("IdNumber");
                idNumber.setText(add11);
                String add2 = rs.getString("AccountBalance");
                jTexBalance.setText(add2);
                String add12 = rs.getString("AccountType");
                jCombacytpe.setSelectedItem(add12);
                String add6 = rs.getString("Contact");
                jTextcontact.setText(add6);



            }


            else {
                JOptionPane.showMessageDialog(this, "Client  with Bank Account Number " + jTextFieldacnim.getText() + " does not exist","Error message",JOptionPane.WARNING_MESSAGE);
                return;
            }
con.close();
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField idNumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCombacytpe;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTexBalance;
    private javax.swing.JTextField jTextFieldacnim;
    private javax.swing.JTextField jTextFieldname;
    private javax.swing.JTextField jTextcontact;
    // End of variables declaration//GEN-END:variables
}
