/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author HYPERLINKS
 */
public class AllDeposits extends javax.swing.JInternalFrame {
   java.sql.Connection con = null;
    ResultSet rs = null;
    java.sql.PreparedStatement pst = null;
    /**
     * Creates new form AllDeposits
     */
    public AllDeposits() {
        initComponents();
        String sql="Select*from bankdeposits";
        fillTableWthdRecords(sql);
    }
     public void fillTableWthdRecords(String QUERRYs) {
        try {
            Connection con = (Connection) DBManager.ConnectDB();
            pst = (PreparedStatement) con.prepareStatement(QUERRYs);
            rs = pst.executeQuery();
            jTabldeposits.setModel(DbUtils.resultSetToTableModel(rs));
            jTabldeposits.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTabldeposits.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTabldeposits.getColumnModel().getColumn(2).setPreferredWidth(250);
            jTabldeposits.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTabldeposits.getColumnModel().getColumn(4).setPreferredWidth(120);
            jTabldeposits.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTabldeposits.getColumnModel().getColumn(6).setPreferredWidth(120);
            jTabldeposits.getColumnModel().getColumn(7).setPreferredWidth(120);



        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
       public void updateSave(String QUERRY) {
        try {
            con = (com.mysql.jdbc.Connection) DBManager.ConnectDB();
            pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(QUERRY);
            pst.execute();
            con.close();
        } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, e);
        }

   }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabldeposits = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        acnum = new javax.swing.JTextField();
        jTextFieldname = new javax.swing.JTextField();
        jTextField7idnum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jDesktopPane1.setOpaque(false);

        jTabldeposits.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTabldeposits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTabldeposits.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTabldeposits.getTableHeader().setResizingAllowed(false);
        jTabldeposits.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTabldeposits);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(0, 190, 960, 260);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("ALL Account Deposits");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(320, 20, 230, 24);

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255)), "Search Single Account", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 12), new java.awt.Color(0, 153, 153))); // NOI18N
        jDesktopPane2.setOpaque(false);

        acnum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane2.add(acnum);
        acnum.setBounds(170, 30, 230, 20);

        jTextFieldname.setEditable(false);
        jTextFieldname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane2.add(jTextFieldname);
        jTextFieldname.setBounds(170, 60, 380, 20);

        jTextField7idnum.setEditable(false);
        jTextField7idnum.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane2.add(jTextField7idnum);
        jTextField7idnum.setBounds(170, 90, 140, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ID Number");
        jDesktopPane2.add(jLabel9);
        jLabel9.setBounds(80, 90, 75, 14);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        jDesktopPane2.add(jLabel1);
        jLabel1.setBounds(110, 60, 31, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Account Number");
        jDesktopPane2.add(jLabel6);
        jLabel6.setBounds(50, 30, 88, 14);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton1);
        jButton1.setBounds(410, 30, 140, 25);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton2.setText("Clear Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane2.add(jButton2);
        jButton2.setBounds(560, 30, 130, 25);

        jDesktopPane1.add(jDesktopPane2);
        jDesktopPane2.setBounds(60, 50, 760, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 962, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            con = (Connection) DBManager.ConnectDB();


            String sql = "select * from bankdeposits where AccountNumber = '" + acnum.getText() + "'";
            pst = (PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {

                String add1 = rs.getString("Name");
                jTextFieldname.setText(add1);
                String add11 = rs.getString("IdNumber");
                jTextField7idnum.setText(add11);


                String QUERRY = "SELECT*FROM `bankdeposits` where AccountNumber='" + acnum.getText() + "'";
                fillTableWthdRecords(QUERRY);
            } else {
                JOptionPane.showMessageDialog(this, "Persons With Account Number  " + acnum.getText() + " does not exist");
                jTextFieldname.setText("");
        acnum.setText("");
        jTextField7idnum.setText("");
        String sql2 = "Select*from bankdeposits";
        fillTableWthdRecords(sql2);
        con.close();
                return;
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextFieldname.setText("");
        acnum.setText("");
        jTextField7idnum.setText("");
        String sql = "Select*from bankdeposits";
        fillTableWthdRecords(sql);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acnum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabldeposits;
    private javax.swing.JTextField jTextField7idnum;
    private javax.swing.JTextField jTextFieldname;
    // End of variables declaration//GEN-END:variables
}
