/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HYPERLINKS
 */
public class casheposit extends javax.swing.JInternalFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form casheposit
     */
    public casheposit() {
        initComponents();
    }
    public void clear(){
 jTexBalance.setText("");
 acnumber.setText("");
jTextFiename.setText("");
jTextidnumber.setText("");
phoneNumber.setText("");
depositAmount.setText("");
((JTextField) jDate.getDateEditor().getUiComponent()).setText("");
jCombacytpe.setSelectedIndex(0);

    }
     public void updateSave(String QUERRY) {
        try {
            con = (com.mysql.jdbc.Connection) DBManager.ConnectDB();
            pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(QUERRY);
            pst.execute();
        } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, e);
        }

   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFiename = new javax.swing.JTextField();
        depositAmount = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        acnumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextidnumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jCombacytpe = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jDate = new com.toedter.calendar.JDateChooser();
        jTexBalance = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jDesktopPane1.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Cash Deposit");
        jDesktopPane1.add(jLabel11);
        jLabel11.setBounds(270, 10, 150, 24);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Account Number");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(60, 60, 88, 14);

        jTextFiename.setEditable(false);
        jTextFiename.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFiename.setForeground(new java.awt.Color(255, 0, 204));
        jDesktopPane1.add(jTextFiename);
        jTextFiename.setBounds(180, 90, 380, 20);

        depositAmount.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        depositAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                depositAmountKeyTyped(evt);
            }
        });
        jDesktopPane1.add(depositAmount);
        depositAmount.setBounds(180, 210, 190, 20);

        phoneNumber.setEditable(false);
        phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(255, 0, 204));
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        jDesktopPane1.add(phoneNumber);
        phoneNumber.setBounds(180, 150, 190, 20);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Phone Number");
        jDesktopPane1.add(jLabel8);
        jLabel8.setBounds(80, 160, 80, 14);

        acnumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jDesktopPane1.add(acnumber);
        acnumber.setBounds(180, 60, 230, 20);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(120, 90, 31, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Amount To Deposit");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(50, 210, 102, 14);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(420, 60, 140, 25);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ID Number");
        jDesktopPane1.add(jLabel9);
        jLabel9.setBounds(90, 120, 75, 14);

        jTextidnumber.setEditable(false);
        jTextidnumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextidnumber.setForeground(new java.awt.Color(255, 0, 204));
        jDesktopPane1.add(jTextidnumber);
        jTextidnumber.setBounds(180, 120, 140, 20);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Account Type");
        jDesktopPane1.add(jLabel14);
        jLabel14.setBounds(330, 120, 71, 14);

        jCombacytpe.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jCombacytpe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select Account type-", "Salary Account", "Current Account" }));
        jCombacytpe.setEnabled(false);
        jDesktopPane1.add(jCombacytpe);
        jCombacytpe.setBounds(410, 120, 150, 20);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton2.setText("New Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(100, 310, 140, 25);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton3.setText("Post Transaction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(jButton3);
        jButton3.setBounds(250, 310, 140, 25);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton4.setText("Roll Back Transaction");
        jDesktopPane1.add(jButton4);
        jButton4.setBounds(400, 310, 150, 25);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Date");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(120, 240, 30, 14);

        jDate.setDateFormatString("yyy-MM-dd");
        jDesktopPane1.add(jDate);
        jDate.setBounds(180, 240, 150, 20);

        jTexBalance.setEditable(false);
        jTexBalance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTexBalance.setForeground(new java.awt.Color(255, 0, 102));
        jDesktopPane1.add(jTexBalance);
        jTexBalance.setBounds(180, 180, 190, 20);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Current  Balance");
        jDesktopPane1.add(jLabel10);
        jLabel10.setBounds(70, 180, 100, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     try{
       if (acnumber.getText().equals("")||jTextFiename.getText().equals("")||depositAmount.getText().equals("")||((JTextField) jDate.getDateEditor().getUiComponent()).getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please Fill All the Fields", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }



     }
     catch(Exception e){

     }




        try{
              int cbalance=Integer.parseInt(jTexBalance.getText());
              int amount=Integer.parseInt(depositAmount.getText());
              int newBalace=amount+cbalance;

                String sql2="INSERT  INTO `bankdeposits`(id,`AccountNumber`, `Name`, `IdNumber`,`AccountType`, `Date` ,`InitialAmount`,Amount, `NewBalance`) VALUES ('0','" + acnumber.getText() + "','" + jTextFiename.getText() + "','" + jTextidnumber.getText() + "','" + jCombacytpe.getSelectedItem() + "','" + ((JTextField) jDate.getDateEditor().getUiComponent()).getText() + "','"+jTexBalance.getText()+"','" + depositAmount.getText() + "','"+newBalace+"') ";

                String sql3="UPDATE mainaccount SET  AccountBalance='"+newBalace+"' WHERE AccountNumber='" + acnumber.getText() + "'";
                 updateSave(sql2);
                 updateSave(sql3);

                JOptionPane.showMessageDialog(this, "Amount has been Deposited Successfuly!!!", "Student Record", JOptionPane.INFORMATION_MESSAGE);
                clear();
               con.close();
              } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{

            con = (com.mysql.jdbc.Connection) DBManager.ConnectDB();


            String sql = "select * from mainaccount where AccountNumber = '" + acnumber.getText() + "'";
            pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {

                String add1 = rs.getString("Name");
                jTextFiename.setText(add1);
                String add11 = rs.getString("IdNumber");
                jTextidnumber.setText(add11);
                String add2 = rs.getString("AccountBalance");
                jTexBalance.setText(add2);
                String add12 = rs.getString("AccountType");
                jCombacytpe.setSelectedItem(add12);
                String add6 = rs.getString("Contact");
                phoneNumber.setText(add6);



            }


            else {
                JOptionPane.showMessageDialog(this, "Client  with Bank Account Number " + acnumber.getText() + " does not exist","Error message",JOptionPane.WARNING_MESSAGE);
                return;
            }
            con.close();
            } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void depositAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_depositAmountKeyTyped
       char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_depositAmountKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acnumber;
    private javax.swing.JTextField depositAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCombacytpe;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTexBalance;
    private javax.swing.JTextField jTextFiename;
    private javax.swing.JTextField jTextidnumber;
    private javax.swing.JTextField phoneNumber;
    // End of variables declaration//GEN-END:variables
}
