/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package banking;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author HYPERLINKS
 */
public class withdraw extends javax.swing.JInternalFrame {
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form withdraw
     */
    public withdraw() {
        initComponents();
    }
   public void clear(){

  acnumber.setText("");
jTextFiename.setText("");
jTextidnumber.setText("");
phoneNumber.setText("");
jTexBalance.setText("");
withdrawamt.setText("");
((JTextField) jDate.getDateEditor().getUiComponent()).setText("");
jCombacytpe.setSelectedIndex(0);
   }

    public void updateSave(String QUERRY) {
        try {
            con = (com.mysql.jdbc.Connection) DBManager.ConnectDB();
            pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(QUERRY);
            pst.execute();
            con.close();
        } catch (SQLException e) {
          JOptionPane.showMessageDialog(null, e);
        }

   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel11 = new javax.swing.JLabel();
        withdrawamt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDate = new com.toedter.calendar.JDateChooser();
        jTextFiename = new javax.swing.JTextField();
        jTextidnumber = new javax.swing.JTextField();
        phoneNumber = new javax.swing.JTextField();
        acnumber = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTexBalance = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCombacytpe = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        jDesktopPane1.setOpaque(false);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 255));
        jLabel11.setText("Cash Withdrawal");
        jLabel11.setBounds(270, 30, 206, 24);
        jDesktopPane1.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        withdrawamt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        withdrawamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                withdrawamtKeyTyped(evt);
            }
        });
        withdrawamt.setBounds(170, 240, 190, 20);
        jDesktopPane1.add(withdrawamt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Date");
        jLabel2.setBounds(110, 270, 40, 14);
        jDesktopPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Amount To Withdraw");
        jLabel3.setBounds(20, 250, 130, 14);
        jDesktopPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton2.setText("New Transaction");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(90, 330, 140, 25);
        jDesktopPane1.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton3.setText("Post Transaction");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.setBounds(240, 330, 140, 25);
        jDesktopPane1.add(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton4.setText("Roll Back Transaction");
        jButton4.setBounds(390, 330, 150, 25);
        jDesktopPane1.add(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jDate.setDateFormatString("yyy-MM-dd");
        jDate.setBounds(170, 270, 150, 20);
        jDesktopPane1.add(jDate, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextFiename.setEditable(false);
        jTextFiename.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextFiename.setForeground(new java.awt.Color(255, 0, 204));
        jTextFiename.setBounds(170, 120, 380, 20);
        jDesktopPane1.add(jTextFiename, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextidnumber.setEditable(false);
        jTextidnumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextidnumber.setForeground(new java.awt.Color(255, 0, 204));
        jTextidnumber.setBounds(170, 150, 140, 20);
        jDesktopPane1.add(jTextidnumber, javax.swing.JLayeredPane.DEFAULT_LAYER);

        phoneNumber.setEditable(false);
        phoneNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        phoneNumber.setForeground(new java.awt.Color(255, 0, 204));
        phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberActionPerformed(evt);
            }
        });
        phoneNumber.setBounds(170, 180, 190, 20);
        jDesktopPane1.add(phoneNumber, javax.swing.JLayeredPane.DEFAULT_LAYER);

        acnumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        acnumber.setBounds(170, 90, 230, 20);
        jDesktopPane1.add(acnumber, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(410, 90, 140, 25);
        jDesktopPane1.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTexBalance.setEditable(false);
        jTexBalance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTexBalance.setForeground(new java.awt.Color(255, 0, 102));
        jTexBalance.setBounds(170, 210, 190, 20);
        jDesktopPane1.add(jTexBalance, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Account Number");
        jLabel6.setBounds(50, 90, 88, 14);
        jDesktopPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        jLabel1.setBounds(110, 120, 31, 14);
        jDesktopPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("ID Number");
        jLabel9.setBounds(80, 150, 75, 14);
        jDesktopPane1.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Phone Number");
        jLabel8.setBounds(70, 190, 80, 14);
        jDesktopPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Current  Balance");
        jLabel10.setBounds(60, 210, 100, 14);
        jDesktopPane1.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCombacytpe.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jCombacytpe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select Account type-", "Salary Account", "Current Account" }));
        jCombacytpe.setEnabled(false);
        jCombacytpe.setBounds(400, 150, 150, 20);
        jDesktopPane1.add(jCombacytpe, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setText("Account Type");
        jLabel14.setBounds(320, 150, 71, 14);
        jDesktopPane1.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            con = (com.mysql.jdbc.Connection) DBManager.ConnectDB();


            String sql = "select * from mainaccount where AccountNumber = '" + acnumber.getText() + "'";
            pst = (com.mysql.jdbc.PreparedStatement) con.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {

                String add1 = rs.getString("Name");
                jTextFiename.setText(add1);
                String add11 = rs.getString("IdNumber");
                jTextidnumber.setText(add11);
                String add2 = rs.getString("AccountBalance");
                jTexBalance.setText(add2);
                String add12 = rs.getString("AccountType");
                jCombacytpe.setSelectedItem(add12);
                String add6 = rs.getString("Contact");
                phoneNumber.setText(add6);



            } else {
                JOptionPane.showMessageDialog(this, "Client  with Bank Account Number " + acnumber.getText() + " does not exist","Error message",JOptionPane.WARNING_MESSAGE);
                return;
            }
con.close();
        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void withdrawamtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_withdrawamtKeyTyped
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_withdrawamtKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
       if (acnumber.getText().equals("")||jTextFiename.getText().equals("")||withdrawamt.getText().equals("")||((JTextField) jDate.getDateEditor().getUiComponent()).getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Please Fill All the Fields", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }



     }
     catch(Exception e){

     }




        try{
              int cbalance=Integer.parseInt(jTexBalance.getText());
              int amount=Integer.parseInt(withdrawamt.getText());
              int newBalace=cbalance-amount;

              if(newBalace<0){
               JOptionPane.showMessageDialog(this, "Account Over Draft", "Error", JOptionPane.ERROR_MESSAGE);
                return;

            }

                String sql2="INSERT  INTO `withdrawals`(id,`AccountNumber`, `Name`, `IdNumber`,`AccountType`, `Date` ,`InitialAmount`,Amount, `NewBalance`) VALUES ('0','" + acnumber.getText() + "','" + jTextFiename.getText() + "','" + jTextidnumber.getText() + "','" + jCombacytpe.getSelectedItem() + "','" + ((JTextField) jDate.getDateEditor().getUiComponent()).getText() + "','"+jTexBalance.getText()+"','" + withdrawamt.getText() + "','"+newBalace+"') ";

                String sql3="UPDATE mainaccount SET  AccountBalance='"+newBalace+"' WHERE AccountNumber='" + acnumber.getText() + "'";
                 updateSave(sql2);
                 updateSave(sql3);

                JOptionPane.showMessageDialog(this, "Amount has been Withdrawn Successfuly!!!", "Student Record", JOptionPane.INFORMATION_MESSAGE);
                clear();

              } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acnumber;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jCombacytpe;
    private com.toedter.calendar.JDateChooser jDate;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTexBalance;
    private javax.swing.JTextField jTextFiename;
    private javax.swing.JTextField jTextidnumber;
    private javax.swing.JTextField phoneNumber;
    private javax.swing.JTextField withdrawamt;
    // End of variables declaration//GEN-END:variables
}
